-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- This file will be auto-generated by drizzle-kit
-- Run: bun run db:generate to create migrations

